// Word frequency data based on common English usage
// Higher scores indicate more common words (scale 1-10)
export const WORD_FREQUENCY_MAP: Record<string, number> = {
  // Common everyday words (frequency 8-10)
  'ABOUT': 10, 'ABOVE': 9, 'ABUSE': 7, 'ACTOR': 8, 'ACUTE': 7, 'ADMIT': 8, 'ADOPT': 7, 'ADULT': 9, 'AFTER': 10, 'AGAIN': 10,
  'AGENT': 8, 'AGREE': 9, 'AHEAD': 8, 'ALARM': 8, 'ALBUM': 8, 'ALERT': 8, 'ALIEN': 8, 'ALIGN': 7, 'ALIKE': 8, 'ALIVE': 9,
  'ALLOW': 9, 'ALONE': 9, 'ALONG': 9, 'ALTER': 7, 'ANGEL': 8, 'ANGER': 8, 'ANGLE': 8, 'ANGRY': 9, 'APART': 8, 'APPLE': 9,
  'APPLY': 8, 'ARENA': 7, 'ARGUE': 8, 'ARISE': 7, 'ARRAY': 7, 'ASIDE': 8, 'ASSET': 7, 'AVOID': 8, 'AWAKE': 8, 'AWARD': 8,
  'AWARE': 9, 'BADLY': 8, 'BAKER': 8, 'BASIC': 9, 'BEACH': 9, 'BEGAN': 9, 'BEGIN': 9, 'BEING': 10, 'BELOW': 9, 'BENCH': 8,
  'BIRTH': 9, 'BLACK': 10, 'BLAME': 8, 'BLANK': 8, 'BLIND': 8, 'BLOCK': 9, 'BLOOD': 9, 'BOARD': 9, 'BOOST': 7, 'BOOTH': 7,
  'BOUND': 8, 'BRAIN': 9, 'BRAND': 8, 'BRASS': 7, 'BRAVE': 8, 'BREAD': 9, 'BREAK': 9, 'BREED': 7, 'BRIEF': 8, 'BRING': 9,
  'BROAD': 8, 'BROKE': 8, 'BROWN': 9, 'BUILD': 9, 'BUILT': 9, 'BUYER': 7, 'CABLE': 8, 'CARRY': 9, 'CATCH': 9, 'CAUSE': 9,
  'CHAIN': 8, 'CHAIR': 9, 'CHAOS': 7, 'CHARM': 8, 'CHART': 8, 'CHASE': 8, 'CHEAP': 8, 'CHECK': 9, 'CHEST': 8, 'CHILD': 10,
  'CHINA': 9, 'CHOSE': 8, 'CIVIL': 8, 'CLAIM': 8, 'CLASS': 9, 'CLEAN': 9, 'CLEAR': 9, 'CLICK': 8, 'CLIMB': 8, 'CLOCK': 9,
  'CLOSE': 9, 'CLOUD': 9, 'COACH': 8, 'COAST': 8, 'COULD': 10, 'COUNT': 9, 'COURT': 9, 'COVER': 9, 'CRAFT': 8, 'CRASH': 8,
  'CRAZY': 9, 'CREAM': 8, 'CRIME': 8, 'CROSS': 9, 'CROWD': 8, 'CROWN': 8, 'CRUDE': 7, 'CURVE': 8, 'CYCLE': 8, 'DAILY': 9,
  'DANCE': 9, 'DATED': 7, 'DEALT': 7, 'DEATH': 9, 'DEBUT': 7, 'DELAY': 8, 'DEPTH': 8, 'DOING': 9, 'DOUBT': 8, 'DOZEN': 8,
  'DRAFT': 7, 'DRAMA': 8, 'DRANK': 8, 'DRAWN': 8, 'DREAM': 9, 'DRESS': 9, 'DRILL': 8, 'DRINK': 9, 'DRIVE': 9, 'DROVE': 8,
  'DYING': 8, 'EAGER': 8, 'EARLY': 9, 'EARTH': 9, 'EIGHT': 9, 'ELITE': 8, 'EMPTY': 9, 'ENEMY': 8, 'ENJOY': 9, 'ENTER': 9,
  'ENTRY': 8, 'EQUAL': 9, 'ERROR': 8, 'EVENT': 9, 'EVERY': 10, 'EXACT': 8, 'EXIST': 8, 'EXTRA': 8, 'FAITH': 8, 'FALSE': 8,
  'FAULT': 7, 'FIBER': 7, 'FIELD': 9, 'FIFTH': 8, 'FIFTY': 8, 'FIGHT': 9, 'FINAL': 9, 'FIRST': 10, 'FIXED': 8, 'FLASH': 8,
  'FLEET': 7, 'FLOOR': 9, 'FLUID': 7, 'FOCUS': 9, 'FORCE': 9, 'FORTH': 8, 'FORTY': 8, 'FORUM': 7, 'FOUND': 9, 'FRAME': 8,
  'FRANK': 8, 'FRAUD': 7, 'FRESH': 9, 'FRONT': 9, 'FRUIT': 9, 'FULLY': 8, 'FUNNY': 9, 'GIANT': 8, 'GIVEN': 9, 'GLASS': 9,
  'GLOBE': 8, 'GOING': 9, 'GRACE': 8, 'GRADE': 8, 'GRAND': 8, 'GRANT': 8, 'GRASS': 9, 'GRAVE': 8, 'GREAT': 10, 'GREEN': 9,
  'GROSS': 8, 'GROUP': 9, 'GROWN': 8, 'GUARD': 8, 'GUESS': 9, 'GUEST': 8, 'GUIDE': 8, 'HAPPY': 10, 'HEART': 9, 'HEAVY': 9,
  'HENCE': 7, 'HORSE': 9, 'HOTEL': 8, 'HOUSE': 10, 'HUMAN': 9, 'IDEAL': 8, 'IMAGE': 9, 'INDEX': 7, 'INNER': 8, 'INPUT': 7,
  'ISSUE': 9, 'JOINT': 8, 'JUDGE': 8, 'KNOWN': 9, 'LABEL': 7, 'LARGE': 9, 'LASER': 7, 'LATER': 9, 'LAUGH': 9, 'LAYER': 7,
  'LEARN': 9, 'LEASE': 7, 'LEAST': 9, 'LEAVE': 9, 'LEGAL': 8, 'LEVEL': 9, 'LIGHT': 10, 'LIMIT': 8, 'LINKS': 7, 'LIVES': 9,
  'LOCAL': 9, 'LOOSE': 8, 'LOWER': 8, 'LUCKY': 8, 'LUNCH': 9, 'LYING': 8, 'MAGIC': 8, 'MAJOR': 9, 'MAKER': 8, 'MARCH': 8,
  'MATCH': 9, 'MAYBE': 9, 'MAYOR': 7, 'MEANT': 8, 'MEDIA': 8, 'METAL': 8, 'MIGHT': 9, 'MINOR': 8, 'MINUS': 7, 'MIXED': 8,
  'MODEL': 8, 'MONEY': 10, 'MONTH': 9, 'MORAL': 8, 'MOTOR': 8, 'MOUNT': 7, 'MOUSE': 8, 'MOUTH': 9, 'MOVED': 8, 'MOVIE': 9,
  'MUSIC': 9, 'NEEDS': 9, 'NEVER': 10, 'NEWLY': 8, 'NIGHT': 10, 'NOISE': 8, 'NORTH': 9, 'NOTED': 7, 'NOVEL': 8, 'NURSE': 8,
  'OCCUR': 7, 'OCEAN': 9, 'OFFER': 9, 'OFTEN': 9, 'ORDER': 9, 'OTHER': 10, 'OUGHT': 8, 'PAINT': 8, 'PANEL': 7, 'PAPER': 9,
  'PARTY': 9, 'PEACE': 9, 'PHASE': 7, 'PHONE': 9, 'PHOTO': 9, 'PIANO': 8, 'PIECE': 9, 'PILOT': 8, 'PITCH': 8, 'PLACE': 10,
  'PLAIN': 8, 'PLANE': 9, 'PLANT': 9, 'PLATE': 9, 'POINT': 9, 'POUND': 8, 'POWER': 9, 'PRESS': 8, 'PRICE': 9, 'PRIDE': 8,
  'PRIME': 8, 'PRINT': 8, 'PRIOR': 7, 'PRIZE': 8, 'PROOF': 8, 'PROUD': 8, 'PROVE': 8, 'QUEEN': 8, 'QUERY': 7, 'QUIET': 9,
  'QUITE': 9, 'RADIO': 8, 'RAISE': 8, 'RANGE': 8, 'RAPID': 7, 'RATIO': 7, 'REACH': 9, 'READY': 9, 'REALM': 7, 'REBEL': 7,
  'REFER': 7, 'RELAX': 8, 'REPAY': 7, 'REPLY': 8, 'RIGHT': 10, 'RIGID': 7, 'RISKY': 7, 'RIVER': 9, 'ROMAN': 7, 'ROUGH': 8,
  'ROUND': 9, 'ROUTE': 8, 'ROYAL': 8, 'RURAL': 7, 'SCALE': 8, 'SCENE': 9, 'SCOPE': 7, 'SCORE': 9, 'SENSE': 9, 'SERVE': 8,
  'SETUP': 7, 'SEVEN': 9, 'SHALL': 8, 'SHAPE': 9, 'SHARE': 9, 'SHARP': 8, 'SHEET': 8, 'SHELF': 8, 'SHELL': 8, 'SHIFT': 8,
  'SHINE': 8, 'SHIRT': 9, 'SHOCK': 8, 'SHOOT': 9, 'SHORT': 9, 'SHOWN': 8, 'SIDES': 8, 'SIGHT': 9, 'SILLY': 8, 'SINCE': 9,
  'SIXTH': 8, 'SIXTY': 8, 'SIZED': 7, 'SKILL': 8, 'SLEEP': 9, 'SLIDE': 8, 'SMALL': 10, 'SMART': 9, 'SMILE': 9, 'SMOKE': 8,
  'SOLID': 8, 'SOLVE': 8, 'SORRY': 9, 'SOUND': 9, 'SOUTH': 9, 'SPACE': 9, 'SPARE': 8, 'SPEAK': 9, 'SPEED': 8, 'SPEND': 8,
  'SPENT': 8, 'SPLIT': 8, 'SPOKE': 8, 'SPORT': 9, 'SQUAD': 7, 'STAFF': 8, 'STAGE': 8, 'STAKE': 7, 'STAND': 9, 'START': 9,
  'STATE': 9, 'STAYS': 8, 'STEAL': 8, 'STEAM': 8, 'STEEL': 8, 'STEEP': 7, 'STEER': 7, 'STERN': 7, 'STICK': 9, 'STILL': 9,
  'STOCK': 8, 'STONE': 9, 'STOOD': 8, 'STORE': 9, 'STORM': 8, 'STORY': 9, 'STRIP': 7, 'STUCK': 8, 'STUDY': 9, 'STUFF': 9,
  'STYLE': 8, 'SUGAR': 9, 'SUITE': 7, 'SUPER': 8, 'SWEET': 9, 'SWIFT': 7, 'SWING': 8, 'SWISS': 7, 'TABLE': 9, 'TAKEN': 9,
  'TASTE': 8, 'TAXES': 8, 'TEACH': 8, 'TEARS': 8, 'TEETH': 8, 'TEXAS': 8, 'THANK': 9, 'THEFT': 7, 'THEIR': 10, 'THEME': 8,
  'THERE': 10, 'THESE': 10, 'THICK': 8, 'THING': 10, 'THINK': 10, 'THIRD': 9, 'THOSE': 10, 'THREE': 10, 'THREW': 8, 'THROW': 9,
  'THUMB': 8, 'TIGHT': 8, 'TIMER': 7, 'TIMES': 9, 'TIRED': 8, 'TITLE': 8, 'TODAY': 9, 'TOKEN': 7, 'TOTAL': 9, 'TOUCH': 9,
  'TOUGH': 8, 'TOWER': 8, 'TRACK': 8, 'TRADE': 8, 'TRAIN': 9, 'TREAT': 8, 'TREND': 7, 'TRIAL': 7, 'TRIBE': 7, 'TRICK': 8,
  'TRIED': 8, 'TRIES': 8, 'TRULY': 8, 'TRUNK': 7, 'TRUST': 9, 'TRUTH': 9, 'TWICE': 8, 'TWIST': 8, 'UNCLE': 8, 'UNDUE': 6,
  'UNION': 8, 'UNITY': 7, 'UNTIL': 9, 'UPPER': 8, 'UPSET': 8, 'URBAN': 8, 'USAGE': 7, 'USUAL': 8, 'VALID': 7, 'VALUE': 9,
  'VIDEO': 9, 'VIRUS': 8, 'VISIT': 9, 'VITAL': 8, 'VOCAL': 7, 'VOICE': 9, 'WASTE': 8, 'WATCH': 9, 'WATER': 10, 'WHEEL': 8,
  'WHERE': 10, 'WHICH': 10, 'WHILE': 9, 'WHITE': 9, 'WHOLE': 9, 'WHOSE': 9, 'WOMAN': 9, 'WOMEN': 9, 'WORLD': 10, 'WORRY': 8,
  'WORSE': 8, 'WORST': 8, 'WORTH': 8, 'WOULD': 10, 'WRITE': 9, 'WRONG': 9, 'WROTE': 8, 'YOUNG': 9, 'YOURS': 8, 'YOUTH': 8,

  // Frequency scores for other common words
  'CABIN': 8, 'CANDY': 9, 'CHAIR': 9, 'DANCE': 9, 'EAGLE': 8, 'FAITH': 8, 'GRACE': 8, 'HABIT': 8, 'IVORY': 7, 'JUDGE': 8,
  'KNIFE': 8, 'LEMON': 8, 'MAPLE': 7, 'NOVEL': 8, 'OCEAN': 9, 'PEACE': 9, 'QUEST': 7, 'RADIO': 8, 'SAINT': 7, 'TIGER': 8,
  'UNCLE': 8, 'VELVET': 7, 'WATER': 10, 'YOUTH': 8, 'ZEBRA': 7,

  // Mark obscure/problematic words with very low scores (1-3)
  'ERVIL': 1, 'EMPTS': 1, 'QOPHS': 1, 'KUFIS': 1, 'JILTS': 2, 'QADIS': 1, 'QERID': 1, 'AAHED': 2, 'ABEAM': 3, 'ABELE': 2,
  'ABETS': 3, 'ABIES': 2, 'ABODE': 6, 'ABOMB': 2, 'ABOON': 1, 'ABRI': 1, 'ABRIN': 1, 'ABRIS': 1, 'ABSIT': 1, 'ABUNA': 1,
  'ABUNE': 1, 'ABYES': 1, 'ACAI': 3, 'ACARI': 2, 'ACCAD': 1, 'ACCOY': 1, 'ACERB': 2, 'ACHED': 7, 'ACHES': 7, 'ACHOO': 4,
  'ACIDS': 5, 'ACIDY': 2, 'ACING': 4, 'ACINI': 1, 'ACKEE': 2, 'ACMES': 3, 'ACNED': 2, 'ACNES': 2, 'ACOCK': 2, 'ACOLD': 1,
  'ACORN': 6, 'ACRED': 2, 'ACRES': 7, 'ACRID': 4, 'ACTIN': 3, 'ACTON': 2, 'ACTOR': 8, 'ACUTE': 7, 'ACYLS': 1, 'ADAGE': 4,
  'ADAPT': 7, 'ADDAX': 1, 'ADDED': 8, 'ADDER': 4, 'ADDIS': 2, 'ADDLE': 3, 'ADEEM': 1, 'ADHAN': 1, 'ADIEU': 4, 'ADIOS': 5,
  'ADITS': 2, 'ADJY': 1, 'ADMIX': 2, 'ADOBE': 5, 'ADOBO': 3, 'ADOPT': 7, 'ADORE': 7, 'ADORN': 6, 'ADOWN': 2, 'ADOZE': 2,
  'ADUKI': 2, 'ADULT': 9, 'ADUNC': 1, 'ADUST': 1, 'ADVEW': 1, 'AECIA': 1, 'AEDES': 1, 'AEGIS': 4, 'AEONS': 3, 'AEROS': 2,
  'AERY': 2, 'AFALD': 1, 'AFAR': 6, 'AFEAR': 2, 'AFFIX': 4, 'AFIRE': 4, 'AFLAJ': 1, 'AFOOT': 5, 'AFORE': 3, 'AFOUL': 3,
  'AFRIT': 1, 'AFROS': 3, 'AFTER': 10, 'AGAIN': 10, 'AGAMA': 1, 'AGAPE': 3, 'AGARS': 2, 'AGATE': 4, 'AGAVE': 3, 'AGAZE': 2,
  'AGENE': 1, 'AGENT': 8, 'AGERS': 2, 'AGGER': 1, 'AGGIE': 3, 'AGGRO': 3, 'AGHAS': 1, 'AGILA': 1, 'AGILE': 6, 'AGING': 6,
  'AGIOS': 1, 'AGISM': 2, 'AGIST': 1, 'AGITA': 2, 'AGLET': 1, 'AGLEY': 2, 'AGLOO': 1, 'AGLOW': 5, 'AGMAS': 1, 'AGONE': 2,
  'AGONS': 1, 'AGONY': 6, 'AGOOD': 2, 'AGORA': 3, 'AGREE': 9, 'AGRIA': 1, 'AGRIN': 2, 'AGRIOS': 1, 'AGUED': 2, 'AGUES': 2,
  'AGUTI': 1, 'AHEAD': 8, 'AHEAP': 1, 'AHENT': 1, 'AHIGH': 1, 'AHIND': 1, 'AHING': 1, 'AHINT': 1, 'AHOLD': 3, 'AHOY': 3,
  'AHS': 2, 'AIDED': 6, 'AIDER': 4, 'AIDES': 5, 'AIDOI': 1, 'AIDOS': 1, 'AIERY': 2, 'AIGHT': 2, 'AILED': 4, 'AIMED': 7,
  'AIMER': 2, 'AINS': 2, 'AIOLI': 4, 'AIRED': 6, 'AIRER': 3, 'AIRNS': 1, 'AIRTH': 1, 'AIRTS': 2, 'AISLE': 7, 'AITCH': 3,
  'AITUS': 1, 'AIVER': 1, 'AIZLE': 1, 'AJAPA': 1, 'AJEE': 1, 'AJIVA': 1, 'AJOG': 1, 'AJUGA': 1, 'AJWAN': 1, 'AKELA': 2,
  'AKENE': 1, 'AKING': 3, 'AKIMBO': 4, 'AKIN': 5, 'ALAND': 2, 'ALANE': 2, 'ALANG': 1, 'ALANS': 1, 'ALANT': 1, 'ALAPA': 1,
  'ALARM': 8, 'ALARY': 1, 'ALATE': 2, 'ALAYS': 1, 'ALBAS': 1, 'ALBEE': 2, 'ALBUM': 8, 'ALCID': 1, 'ALDER': 5, 'ALDOL': 1,
  'ALECK': 3, 'ALECS': 2, 'ALEFS': 1, 'ALEFT': 1, 'ALEPH': 2, 'ALERT': 8, 'ALEWS': 1, 'ALEYE': 1, 'ALFAS': 2, 'ALGAE': 5,
  'ALGAL': 3, 'ALGAS': 3, 'ALGOR': 1, 'ALGUM': 1, 'ALIAS': 5, 'ALIBI': 5, 'ALIEN': 8, 'ALIEF': 1, 'ALIFS': 1, 'ALIGN': 7,
  'ALIKE': 8, 'ALINE': 4, 'ALIST': 1, 'ALIVE': 9, 'ALIYA': 2, 'ALKIE': 2, 'ALKIS': 1, 'ALKYD': 1, 'ALKYL': 2, 'ALLAY': 4,
  'ALLEE': 2, 'ALLEL': 1, 'ALLEY': 7, 'ALLIS': 1, 'ALLOD': 1, 'ALLOT': 5, 'ALLOW': 9, 'ALLOY': 5, 'ALLYL': 2, 'ALMAH': 1,
  'ALMAS': 1, 'ALMEH': 1, 'ALMES': 1, 'ALMUD': 1, 'ALMUG': 1, 'ALNICO': 1, 'ALODS': 1, 'ALOED': 1, 'ALOES': 3, 'ALOFT': 5,
  'ALOHA': 6, 'ALOIN': 1, 'ALONE': 9, 'ALONG': 9, 'ALOOF': 6, 'ALOUD': 7, 'ALOWE': 1, 'ALPHA': 6, 'ALTAR': 6, 'ALTER': 7,
  'ALTS': 2, 'ALULA': 1, 'ALUMS': 3, 'ALURE': 1, 'ALWAY': 4, 'AMAHS': 1, 'AMAIN': 2, 'AMASS': 4, 'AMAZE': 7, 'AMBER': 6,
  'AMBIT': 3, 'AMBLE': 5, 'AMBOS': 1, 'AMBRY': 1, 'AMEBA': 3, 'AMEND': 6, 'AMENS': 4, 'AMENT': 2, 'AMIAS': 1, 'AMICE': 1,
  'AMICI': 1, 'AMIDE': 3, 'AMIDO': 1, 'AMIDS': 2, 'AMIES': 1, 'AMIGA': 2, 'AMIGO': 5, 'AMINE': 3, 'AMINO': 4, 'AMINS': 2,
  'AMIRS': 1, 'AMISS': 5, 'AMITY': 4, 'AMMAN': 2, 'AMMON': 2, 'AMMOS': 1, 'AMNIO': 2, 'AMOKS': 2, 'AMOLE': 1, 'AMONG': 9,
  'AMORT': 2, 'AMOUR': 4, 'AMPED': 4, 'AMPLE': 7, 'AMPLY': 6, 'AMPUL': 1, 'AMRIT': 1, 'AMUCK': 3, 'AMUSE': 7, 'AMUSIA': 1,
  'AMYLS': 1, 'ANANA': 1, 'ANCHO': 2, 'ANCON': 1, 'ANDED': 2, 'ANGEL': 8, 'ANGER': 8, 'ANGLE': 8, 'ANGLO': 4, 'ANGRY': 9,
  'ANGST': 5, 'ANIGH': 2, 'ANILE': 2, 'ANILS': 1, 'ANIMA': 3, 'ANIME': 6, 'ANION': 3, 'ANISE': 4, 'ANKER': 1, 'ANKLE': 7,
  'ANLAS': 1, 'ANNAL': 2, 'ANNAS': 2, 'ANNAT': 1, 'ANNEX': 5, 'ANNOY': 7, 'ANNUL': 4, 'ANOAS': 1, 'ANODE': 4, 'ANOLE': 2,
  'ANOMY': 2, 'ANSAE': 1, 'ANTAE': 1, 'ANTAR': 1, 'ANTAS': 1, 'ANTED': 3, 'ANTES': 3, 'ANTIC': 4, 'ANTIS': 2, 'ANTRA': 1,
  'ANTRE': 2, 'ANTSY': 4, 'ANURA': 1, 'ANVIL': 5, 'ANYON': 1, 'AORTA': 4, 'APACE': 3, 'APAGE': 1, 'APAID': 1, 'APART': 8,
  'APAYD': 1, 'APAYS': 1, 'APEAK': 1, 'APEEK': 1, 'APERS': 1, 'APERT': 2, 'APERY': 2, 'APHID': 4, 'APHIS': 2, 'APIAN': 1,
  'APING': 3, 'APIOL': 1, 'APISH': 3, 'APISM': 1, 'APNEA': 4, 'APODE': 1, 'APODS': 1, 'APOOP': 1, 'APORT': 2, 'APPAL': 1,
  'APPAY': 1, 'APPEL': 2, 'APPLE': 9, 'APPLY': 8, 'APPRO': 1, 'APPUI': 1, 'APRES': 2, 'APRON': 7, 'APSES': 2, 'APSIS': 2,
  'APTER': 3, 'APTLY': 5, 'AQUAE': 1, 'AQUAS': 2, 'ARABA': 1, 'ARACK': 1, 'ARAME': 1, 'ARARS': 1, 'ARBOR': 5, 'ARCED': 3,
  'ARCHI': 1, 'ARCOS': 1, 'ARCUS': 1, 'ARDEB': 1, 'ARDOR': 5, 'ARDRI': 1, 'AREAD': 2, 'AREAE': 1, 'AREAL': 4, 'AREAR': 1,
  'AREAS': 8, 'ARECA': 1, 'AREDD': 1, 'AREDE': 1, 'AREFY': 1, 'AREIC': 1, 'ARENA': 7, 'ARERE': 1, 'ARETE': 2, 'ARETH': 1,
  'ARGAL': 1, 'ARGAN': 2, 'ARGIL': 1, 'ARGLE': 1, 'ARGOL': 1, 'ARGON': 3, 'ARGOT': 3, 'ARGUE': 8, 'ARGUS': 2, 'ARHAT': 1,
  'ARIAS': 3, 'ARIEL': 4, 'ARIKI': 1, 'ARILS': 1, 'ARIOT': 1, 'ARISE': 7, 'ARISH': 1, 'ARKED': 2, 'ARLES': 1, 'ARMED': 7,
  'ARMER': 2, 'ARMET': 1, 'ARMIL': 1, 'ARMOR': 6, 'ARNAS': 1, 'ARNUT': 1, 'AROBA': 1, 'AROHA': 1, 'AROID': 1, 'AROMA': 6,
  'AROSE': 7, 'ARPAS': 1, 'ARPEN': 1, 'ARPS': 1, 'ARRAS': 2, 'ARRAY': 7, 'ARRET': 1, 'ARRIS': 1, 'ARROW': 7, 'ARROZ': 1,
  'ARSED': 2, 'ARSES': 3, 'ARSEY': 2, 'ARSIS': 2, 'ARSON': 5, 'ARTAL': 1, 'ARTEL': 1, 'ARTERY': 6, 'ARTSY': 4, 'ARUM': 2,
  'ARUMS': 2, 'ARVAL': 1, 'ARVOS': 1, 'ARYLS': 1, 'ASANA': 3, 'ASCI': 1, 'ASCOT': 4, 'ASCUS': 1, 'ASDIC': 1, 'ASHED': 3,
  'ASHEN': 5, 'ASHES': 6, 'ASHET': 1, 'ASIDE': 8, 'ASKED': 9, 'ASKER': 5, 'ASKEW': 5, 'ASKOI': 1, 'ASKOS': 1, 'ASPEN': 5,
  'ASPER': 2, 'ASPIC': 3, 'ASPIS': 1, 'ASPRO': 1, 'ASSAI': 1, 'ASSAM': 2, 'ASSAY': 4, 'ASSES': 4, 'ASSET': 7, 'ASSEZ': 1,
  'ASSOT': 1, 'ASTER': 4, 'ASTIR': 4, 'ASTUN': 1, 'ASWAY': 2, 'ASWIM': 2, 'ASYLA': 1, 'ATAMAN': 1, 'ATAPS': 1, 'ATAXY': 1,
  'ATIGI': 1, 'ATILT': 3, 'ATIMY': 1, 'ATLAS': 6, 'ATMAN': 2, 'ATMAS': 1, 'ATOCS': 1, 'ATOKE': 1, 'ATOKS': 1, 'ATOLL': 4,
  'ATOMS': 6, 'ATOMY': 2, 'ATONE': 5, 'ATONY': 2, 'ATOPY': 2, 'ATRIA': 3, 'ATRIP': 2, 'ATTAP': 1, 'ATTAR': 2, 'ATTIC': 6,
  'ATUAS': 1, 'AUDAD': 1, 'AUDIO': 7, 'AUDIT': 6, 'AUGER': 3, 'AUGHT': 4, 'AUGUR': 3, 'AULAS': 1, 'AULD': 3, 'AULOI': 1,
  'AULOS': 1, 'AUNES': 1, 'AUNTS': 6, 'AUNTY': 6, 'AURAE': 1, 'AURAL': 4, 'AURAR': 1, 'AURAS': 4, 'AUREI': 1, 'AURES': 1,
  'AURIC': 2, 'AURIS': 1, 'AURUM': 2, 'AUTOS': 5, 'AUXIN': 2, 'AVAIL': 6, 'AVANT': 3, 'AVAST': 3, 'AVELS': 1, 'AVENS': 2,
  'AVERS': 2, 'AVERT': 5, 'AVGAS': 1, 'AVIAN': 4, 'AVION': 2, 'AVISE': 1, 'AVISO': 1, 'AVIZE': 1, 'AVOID': 8, 'AVOWS': 3,
  'AWABA': 1, 'AWAKE': 8, 'AWAMI': 1, 'AWARD': 8, 'AWARN': 1, 'AWASH': 5, 'AWATO': 1, 'AWAVE': 1, 'AWAYS': 4, 'AWDLS': 1,
  'AWEEL': 1, 'AWETO': 1, 'AWFUL': 7, 'AWING': 3, 'AWMOUS': 1, 'AWNED': 2, 'AWNER': 1, 'AWNY': 1, 'AWOKE': 7, 'AWOL': 3,
  'AWORK': 2, 'AXELS': 2, 'AXIAL': 4, 'AXILE': 2, 'AXILS': 2, 'AXING': 3, 'AXION': 2, 'AXITE': 1, 'AXLED': 2, 'AXLES': 4,
  'AXMAN': 2, 'AXMEN': 2, 'AXOID': 1, 'AXON': 3, 'AXONE': 2, 'AXONS': 3, 'AYAHS': 1, 'AYAYA': 1, 'AYELP': 1, 'AYGRE': 1,
  'AYINS': 1, 'AYONT': 1, 'AYRES': 1, 'AYRIE': 1, 'AZANS': 1, 'AZIDE': 2, 'AZIDO': 1, 'AZINE': 1, 'AZLON': 1, 'AZOIC': 1,
  'AZOLE': 1, 'AZONS': 1, 'AZOTE': 2, 'AZOTH': 2, 'AZUKI': 2, 'AZURE': 5, 'AZURN': 1, 'AZURY': 1, 'AZYGY': 1, 'AZYME': 1,
  'AZYMS': 1, 'BAAED': 2, 'BAALS': 1, 'BABAS': 2, 'BABEL': 4, 'BABES': 5, 'BABKA': 2, 'BABOO': 1, 'BABUL': 1, 'BABUS': 1,
  'BACCA': 1, 'BACCO': 1, 'BACCY': 2, 'BACHA': 1, 'BACHS': 1, 'BACKS': 7, 'BACON': 8, 'BADDY': 3, 'BADGE': 6, 'BADLY': 8,
  'BAELS': 1, 'BAFFS': 1, 'BAFFY': 1, 'BAFTS': 1, 'BAGEL': 7, 'BAGGY': 5, 'BAGHS': 1, 'BAGIE': 1, 'BAHTS': 1, 'BAHUT': 1,
  'BAILS': 4, 'BAIRN': 3, 'BAISA': 1, 'BAITH': 1, 'BAITS': 4, 'BAIZA': 1, 'BAIZE': 3, 'BAJRA': 1, 'BAJRI': 1, 'BAJUS': 1,
  'BAKED': 8, 'BAKEN': 2, 'BAKER': 8, 'BAKES': 6, 'BAKRA': 1, 'BALAS': 1, 'BALDS': 2, 'BALDY': 3, 'BALED': 3, 'BALER': 2,
  'BALES': 4, 'BALKS': 3, 'BALKY': 3, 'BALLS': 7, 'BALLY': 4, 'BALMS': 3, 'BALMY': 5, 'BALOO': 1, 'BALSA': 4, 'BALTI': 2,
  'BALUN': 1, 'BALUS': 1, 'BAMBI': 4, 'BANAK': 1, 'BANAL': 4, 'BANCO': 2, 'BANCS': 1, 'BANDA': 2, 'BANDH': 1, 'BANDS': 7,
  'BANDY': 4, 'BANED': 2, 'BANES': 3, 'BANGS': 5, 'BANIA': 1, 'BANJO': 6, 'BANKS': 8, 'BANNS': 3, 'BANTU': 3, 'BANTY': 2,
  'BANYA': 1, 'BAPUS': 1, 'BARBE': 1, 'BARBS': 4, 'BARBY': 3, 'BARCA': 1, 'BARDE': 1, 'BARDO': 1, 'BARDS': 3, 'BARDY': 1,
  'BARED': 5, 'BARER': 4, 'BARES': 4, 'BARFS': 3, 'BARGE': 5, 'BARIS': 1, 'BARIT': 1, 'BARKS': 4, 'BARKY': 2, 'BARMS': 2,
  'BARMY': 3, 'BARNS': 6, 'BARNY': 3, 'BARON': 6, 'BARPS': 1, 'BARRA': 2, 'BARRE': 3, 'BARRS': 1, 'BARRY': 4, 'BARYE': 1,
  'BASAN': 1, 'BASED': 8, 'BASER': 4, 'BASES': 7, 'BASHO': 1, 'BASIC': 9, 'BASIJ': 1, 'BASIL': 6, 'BASIN': 6, 'BASIS': 8,
  'BASKS': 3, 'BASON': 2, 'BASSE': 2, 'BASSI': 2, 'BASSO': 3, 'BASSY': 2, 'BASTA': 2, 'BASTE': 5, 'BASTI': 1, 'BASTO': 1,
  'BASTS': 2, 'BATCH': 6, 'BATED': 4, 'BATER': 2, 'BATES': 3, 'BATHE': 7, 'BATHS': 6, 'BATIK': 4, 'BATOK': 1, 'BATON': 5,
  'BATTS': 1, 'BATTU': 1, 'BATTY': 4, 'BAUDS': 1, 'BAUKS': 1, 'BAULK': 2, 'BAWDS': 2, 'BAWDY': 4, 'BAWKS': 1, 'BAWLS': 2,
  'BAWNS': 1, 'BAWRS': 1, 'BAYED': 3, 'BAYOU': 5, 'BAYTS': 1, 'BAZAR': 4, 'BAZOO': 2, 'BEACH': 9, 'BEADS': 6, 'BEADY': 4,
  'BEAGLE': 6, 'BEAKS': 4, 'BEAKY': 3, 'BEAMS': 6, 'BEAMY': 3, 'BEANS': 8, 'BEANY': 3, 'BEARD': 7, 'BEARS': 8, 'BEAST': 7,
  'BEATS': 8, 'BEATY': 3, 'BEAUS': 3, 'BEAUT': 3, 'BEAUX': 4, 'BEBOP': 4, 'BECAP': 1, 'BECKE': 1, 'BECKS': 1, 'BEDAD': 1,
  'BEDEL': 1, 'BEDES': 1, 'BEDEW': 2, 'BEDIM': 2, 'BEDS': 7, 'BEDU': 1, 'BEDYE': 1, 'BEECH': 6, 'BEEDI': 1, 'BEEFS': 5,
  'BEEFY': 5, 'BEEPS': 4, 'BEERS': 8, 'BEERY': 4, 'BEETS': 6, 'BEFOG': 2, 'BEGAN': 9, 'BEGAT': 3, 'BEGET': 4, 'BEGIN': 9,
  'BEGOT': 3, 'BEGUM': 2, 'BEGUN': 7, 'BEHALF': 8, 'BEHELD': 6, 'BEIGE': 6, 'BEIGY': 2, 'BEING': 10, 'BEKAH': 1, 'BELAH': 1,
  'BELAR': 1, 'BELAY': 3, 'BELCH': 5, 'BELDS': 1, 'BELES': 1, 'BELGA': 1, 'BELLS': 7, 'BELLY': 8, 'BELOW': 9, 'BELTS': 6,
  'BEMAD': 1, 'BEMAS': 1, 'BEMIX': 1, 'BEMUD': 1, 'BENCH': 8, 'BENDS': 6, 'BENDY': 4, 'BENES': 1, 'BENET': 1, 'BENGS': 1,
  'BENIS': 1, 'BENNE': 1, 'BENNI': 1, 'BENNY': 3, 'BENTO': 3, 'BENTS': 3, 'BENTY': 2, 'BEPAT': 1, 'BEQET': 1, 'BERES': 1,
  'BERET': 5, 'BERGS': 3, 'BERKO': 1, 'BERKS': 1, 'BERME': 1, 'BERMS': 2, 'BERRY': 8, 'BERTH': 5, 'BERYL': 4, 'BESES': 1,
  'BESET': 5, 'BESOM': 2, 'BESOT': 2, 'BESTS': 4, 'BETAS': 3, 'BETED': 1, 'BETEL': 3, 'BETES': 1, 'BETHS': 1, 'BETON': 1,
  'BETTA': 2, 'BETTY': 4, 'BEVAN': 1, 'BEVEL': 4, 'BEVER': 2, 'BEVOR': 1, 'BEVUE': 1, 'BEVVY': 2, 'BEWET': 1, 'BEWIG': 1,
  'BEZEL': 3, 'BEZIL': 1, 'BEZZY': 2, 'BHAJI': 3, 'BHANG': 2, 'BHATS': 1, 'BHEL': 1, 'BHOOT': 1, 'BHUNA': 2, 'BHUT': 1,
  'BIALY': 2, 'BIBBS': 2, 'BIBES': 1, 'BIBLE': 7, 'BICEP': 6, 'BICES': 1, 'BIDDY': 3, 'BIDED': 3, 'BIDER': 2, 'BIDES': 3,
  'BIDET': 4, 'BIDIS': 1, 'BIDON': 1, 'BIELD': 2, 'BIERS': 2, 'BIFFO': 1, 'BIFFS': 2, 'BIFFY': 1, 'BIFID': 2, 'BIGAE': 1,
  'BIGAS': 1, 'BIGGY': 3, 'BIGHT': 4, 'BIGLY': 3, 'BIGOS': 1, 'BIGOT': 5, 'BIJOU': 3, 'BIKED': 5, 'BIKER': 6, 'BIKES': 7,
  'BIKIE': 2, 'BILBO': 2, 'BILBY': 2, 'BILED': 2, 'BILES': 2, 'BILGE': 4, 'BILGY': 2, 'BILKS': 2, 'BILLS': 8, 'BILLY': 6,
  'BIMBO': 4, 'BINAL': 1, 'BINDI': 2, 'BINDS': 6, 'BINER': 1, 'BINES': 2, 'BINGE': 6, 'BINGO': 6, 'BINGY': 1, 'BINIT': 1,
  'BINKS': 2, 'BINNS': 1, 'BINTS': 1, 'BIOGS': 1, 'BIOME': 4, 'BIONT': 1, 'BIOTA': 3, 'BIPED': 4, 'BIPOD': 3, 'BIRCH': 6,
  'BIRDS': 9, 'BIRKS': 2, 'BIRLE': 1, 'BIRLS': 1, 'BIROS': 2, 'BIRRS': 1, 'BIRSE': 1, 'BIRTH': 9, 'BISES': 1, 'BISKS': 1,
  'BISOM': 1, 'BISON': 6, 'BITCH': 5, 'BITER': 5, 'BITES': 6, 'BITOS': 1, 'BITOU': 1, 'BITSY': 3, 'BITTE': 1, 'BITTS': 1,
  'BITTY': 4, 'BIVAR': 1, 'BIZES': 1, 'BIZZO': 1, 'BIZZY': 2, 'BLABS': 3, 'BLACK': 10, 'BLADE': 7, 'BLADS': 1, 'BLADY': 1,
  'BLAES': 1, 'BLAFF': 1, 'BLAGS': 1, 'BLAHS': 2, 'BLAIN': 2, 'BLAIR': 4, 'BLAKE': 4, 'BLAME': 8, 'BLAMS': 1, 'BLAND': 6,
  'BLANK': 8, 'BLARE': 5, 'BLART': 1, 'BLASE': 4, 'BLAST': 7, 'BLAT': 2, 'BLATE': 2, 'BLATS': 2, 'BLATT': 1, 'BLAUD': 1,
  'BLAZE': 7, 'BLEAK': 6, 'BLEAT': 4, 'BLEBS': 1, 'BLECK': 1, 'BLEDS': 1, 'BLEED': 7, 'BLEEP': 4, 'BLEES': 1, 'BLEND': 7,
  'BLENT': 2, 'BLERT': 1, 'BLESS': 8, 'BLEST': 5, 'BLETS': 1, 'BLEW': 6, 'BLIMP': 4, 'BLIND': 8, 'BLING': 5, 'BLINK': 7,
  'BLINS': 1, 'BLINY': 1, 'BLIPS': 3, 'BLISS': 7, 'BLITE': 2, 'BLITS': 1, 'BLITZ': 6, 'BLIVE': 1, 'BLOAT': 5, 'BLOBS': 4,
  'BLOC': 4, 'BLOCK': 9, 'BLOCS': 3, 'BLOGS': 6, 'BLOKE': 5, 'BLOND': 6, 'BLOOD': 9, 'BLOOK': 1, 'BLOOM': 7, 'BLOOP': 2,
  'BLORE': 1, 'BLOTS': 4, 'BLOWN': 7, 'BLOWS': 6, 'BLOWY': 3, 'BLUBS': 2, 'BLUDE': 1, 'BLUDS': 1, 'BLUDY': 1, 'BLUED': 3,
  'BLUER': 4, 'BLUES': 7, 'BLUET': 2, 'BLUEY': 3, 'BLUFF': 6, 'BLUME': 2, 'BLUNK': 1, 'BLUNT': 6, 'BLURB': 4, 'BLURS': 4,
  'BLURT': 5, 'BLUSH': 7, 'BLYPE': 1, 'BOABS': 1, 'BOAKS': 1, 'BOARD': 9, 'BOARS': 4, 'BOART': 1, 'BOAST': 6, 'BOATS': 8,
  'BOBAC': 1, 'BOBAK': 1, 'BOBAS': 1, 'BOBBY': 6, 'BOBOS': 2, 'BOCCA': 1, 'BOCCE': 3, 'BOCHE': 2, 'BOCKS': 2, 'BODED': 3,
  'BODES': 3, 'BODGE': 2, 'BODHI': 2, 'BODLE': 1, 'BOEPS': 1, 'BOERS': 2, 'BOEUF': 2, 'BOFFO': 1, 'BOFFS': 1, 'BOGAN': 2,
  'BOGEY': 5, 'BOGGY': 3, 'BOGIE': 3, 'BOGLE': 2, 'BOGUS': 5, 'BOHEA': 1, 'BOHOS': 1, 'BOILS': 6, 'BOING': 3, 'BOINK': 2,
  'BOITE': 1, 'BOKED': 1, 'BOKEH': 2, 'BOKES': 1, 'BOKOS': 1, 'BOLAR': 1, 'BOLAS': 2, 'BOLDS': 3, 'BOLES': 2, 'BOLLS': 2,
  'BOLOS': 2, 'BOLTS': 6, 'BOLUS': 3, 'BOMAS': 1, 'BOMBE': 2, 'BOMBS': 6, 'BONCE': 2, 'BONDS': 7, 'BONED': 4, 'BONER': 4,
  'BONES': 8, 'BONGS': 3, 'BONIE': 2, 'BONKS': 3, 'BONNE': 2, 'BONNY': 5, 'BONUS': 7, 'BONZE': 1, 'BOOBS': 5, 'BOOBY': 4,
  'BOODY': 2, 'BOOED': 3, 'BOOFY': 1, 'BOOGY': 3, 'BOOHS': 1, 'BOOKS': 9, 'BOOKY': 2, 'BOOLS': 1, 'BOOMS': 6, 'BOOMY': 3,
  'BOONG': 1, 'BOONS': 3, 'BOORD': 1, 'BOORS': 3, 'BOOSE': 2, 'BOOST': 7, 'BOOTH': 7, 'BOOTS': 8, 'BOOTY': 5, 'BOOZE': 5,
  'BOOZY': 4, 'BORAL': 1, 'BORAS': 1, 'BORAX': 4, 'BORDE': 1, 'BORDS': 1, 'BORED': 7, 'BOREE': 1, 'BOREL': 1, 'BORER': 3,
  'BORES': 5, 'BORGO': 1, 'BORIC': 2, 'BORKS': 1, 'BORMS': 1, 'BORNA': 1, 'BORNE': 6, 'BORON': 3, 'BORTS': 1, 'BORTY': 1,
  'BORTZ': 1, 'BOSIE': 1, 'BOSKS': 1, 'BOSKY': 2, 'BOSOM': 6, 'BOSON': 2, 'BOSSY': 5, 'BOSUN': 3, 'BOTAS': 1, 'BOTCH': 4,
  'BOTEL': 1, 'BOTES': 1, 'BOTHY': 3, 'BOTTS': 1, 'BOTTY': 3, 'BOTUL': 1, 'BOUAT': 1, 'BOUCH': 1, 'BOUFE': 1, 'BOUGH': 5,
  'BOUK': 1, 'BOUKS': 1, 'BOULE': 2, 'BOULT': 1, 'BOUND': 8, 'BOUNS': 1, 'BOURD': 1, 'BOURG': 2, 'BOURN': 2, 'BOUSE': 1,
  'BOUSY': 1, 'BOUTS': 4, 'BOVID': 1, 'BOWAT': 1, 'BOWED': 5, 'BOWEL': 6, 'BOWER': 4, 'BOWES': 1, 'BOWET': 1, 'BOWIE': 3,
  'BOWLS': 6, 'BOWNE': 1, 'BOWRS': 1, 'BOWSE': 1, 'BOWSY': 1, 'BOXED': 5, 'BOXEN': 2, 'BOXER': 6, 'BOXES': 7, 'BOYAR': 2,
  'BOYAU': 1, 'BOYED': 2, 'BOYFS': 1, 'BOYGS': 1, 'BOYLA': 1, 'BOYOS': 2, 'BOYSY': 1, 'BOZOS': 3, 'BRAAI': 2, 'BRAAL': 1,
  'BRABS': 1, 'BRACE': 7, 'BRACH': 1, 'BRACK': 2, 'BRACS': 1, 'BRACT': 2, 'BRADS': 2, 'BRAES': 2, 'BRAGS': 4, 'BRAID': 6,
  'BRAIL': 2, 'BRAIN': 9, 'BRAKE': 7, 'BRAKS': 1, 'BRAKY': 1, 'BRAME': 1, 'BRAND': 8, 'BRANE': 1, 'BRANK': 1, 'BRANS': 2,
  'BRANT': 2, 'BRASH': 4, 'BRASS': 7, 'BRAST': 1, 'BRATS': 4, 'BRAVA': 3, 'BRAVE': 8, 'BRAVI': 1, 'BRAVO': 5, 'BRAWL': 5,
  'BRAWN': 5, 'BRAWS': 1, 'BRAXY': 1, 'BRAYS': 2, 'BRAZA': 1, 'BRAZE': 4, 'BREAD': 9, 'BREAK': 9, 'BREAM': 3, 'BREAR': 1,
  'BREDE': 1, 'BREDS': 1, 'BREED': 7, 'BREEM': 1, 'BREER': 1, 'BREES': 1, 'BREID': 1, 'BREIS': 1, 'BREME': 1, 'BRENS': 1,
  'BRENT': 3, 'BRERE': 1, 'BRERS': 1, 'BRESS': 1, 'BREST': 1, 'BREVE': 2, 'BREWS': 5, 'BREYS': 1, 'BRIAR': 4, 'BRIBE': 5,
  'BRICK': 8, 'BRIDE': 7, 'BRIEF': 8, 'BRIER': 4, 'BRIES': 4, 'BRIGS': 2, 'BRIKS': 1, 'BRILL': 4, 'BRIMS': 3, 'BRINE': 5,
  'BRING': 9, 'BRINK': 6, 'BRINS': 2, 'BRINY': 4, 'BRIOS': 2, 'BRISK': 6, 'BRISS': 1, 'BRITS': 3, 'BRITT': 2, 'BRIZE': 1,
  'BROAD': 8, 'BROCH': 1, 'BROCK': 3, 'BRODS': 1, 'BROGH': 1, 'BROGS': 1, 'BROIL': 5, 'BROKE': 8, 'BROME': 2, 'BROMO': 2,
  'BRONC': 2, 'BROND': 1, 'BROOD': 6, 'BROOK': 7, 'BROOM': 7, 'BROOS': 1, 'BROSE': 1, 'BROSY': 1, 'BROTH': 6, 'BROWS': 6,
  'BROWY': 1, 'BRRRR': 3, 'BRUGH': 1, 'BRUIN': 3, 'BRUIT': 3, 'BRULE': 1, 'BRUME': 2, 'BRUNG': 2, 'BRUNK': 1, 'BRUNS': 1,
  'BRUNT': 5, 'BRURY': 1, 'BRUSH': 8, 'BRUSK': 2, 'BRUST': 1, 'BRUTE': 6, 'BRUTS': 1, 'BRUX': 1, 'BUATS': 1, 'BUAZE': 1,
  'BUBAL': 1, 'BUBAS': 1, 'BUBBA': 4, 'BUBBE': 1, 'BUBBY': 3, 'BUBES': 1, 'BUBO': 1, 'BUBOS': 1, 'BUBUS': 1, 'BUCHU': 1,
  'BUCKO': 2, 'BUCKS': 6, 'BUCKU': 1, 'BUDDY': 7, 'BUDGE': 5, 'BUDGY': 2, 'BUDOS': 1, 'BUFFA': 1, 'BUFFE': 1, 'BUFFI': 1,
  'BUFFO': 1, 'BUFFS': 3, 'BUFFY': 3, 'BUFOS': 1, 'BUFTY': 1, 'BUGGY': 6, 'BUGLE': 5, 'BUHLS': 1, 'BUHRS': 1, 'BUILD': 9,
  'BUILT': 9, 'BUIKS': 1, 'BUIST': 1, 'BUKES': 1, 'BUKSH': 1, 'BULB': 5, 'BULBS': 5, 'BULGE': 5, 'BULGY': 3, 'BULKS': 4,
  'BULKY': 5, 'BULLA': 2, 'BULLS': 6, 'BULLY': 6, 'BULSE': 1, 'BUMBO': 1, 'BUMFS': 1, 'BUMPH': 1, 'BUMPS': 5, 'BUMPY': 5,
  'BUNAS': 1, 'BUNCE': 1, 'BUNCH': 7, 'BUNCO': 2, 'BUNDE': 1, 'BUNDH': 1, 'BUNDS': 1, 'BUNDT': 2, 'BUNDU': 1, 'BUNDY': 2,
  'BUNGS': 2, 'BUNGY': 3, 'BUNIA': 1, 'BUNJE': 1, 'BUNKO': 1, 'BUNKS': 4, 'BUNNS': 1, 'BUNNY': 7, 'BUNTS': 2, 'BUNTY': 1,
  'BUNYA': 1, 'BUOYS': 4, 'BUPPY': 1, 'BUQSHA': 1, 'BURAN': 1, 'BURAS': 1, 'BURBS': 2, 'BURDA': 1, 'BURDS': 1, 'BURET': 1,
  'BURFI': 1, 'BURGH': 3, 'BURGS': 2, 'BURIN': 2, 'BURKA': 2, 'BURKE': 3, 'BURKS': 1, 'BURLS': 2, 'BURLY': 5, 'BURNS': 6,
  'BURNT': 6, 'BUROO': 1, 'BURPS': 3, 'BURQA': 2, 'BURR': 3, 'BURRA': 1, 'BURRO': 3, 'BURRS': 2, 'BURRY': 3, 'BURSA': 3,
  'BURSE': 1, 'BURST': 7, 'BUSBY': 3, 'BUSED': 3, 'BUSES': 6, 'BUSHY': 5, 'BUSHY': 5, 'BUSKS': 2, 'BUSKY': 1, 'BUSON': 1,
  'BUSS': 2, 'BUSSE': 1, 'BUSTS': 4, 'BUSTY': 4, 'BUTCH': 4, 'BUTEO': 1, 'BUTES': 1, 'BUTLE': 1, 'BUTOH': 1, 'BUTTE': 3,
  'BUTTS': 4, 'BUTTY': 3, 'BUTUT': 1, 'BUTYL': 2, 'BUZZY': 3, 'BWANA': 2, 'BWAZI': 1, 'BYDED': 1, 'BYES': 3, 'BYKED': 1,
  'BYKES': 1, 'BYLAW': 4, 'BYNES': 1, 'BYRES': 1, 'BYRLS': 1, 'BYWAY': 4, 'BYWORD': 4, 'BYWORK': 2, 'BYZANTS': 1

  // Continue pattern for more words...
};

// Default frequency for words not in the map
export const DEFAULT_FREQUENCY = 5;

// Minimum frequency thresholds
export const MIN_ANSWER_FREQUENCY = 6;  // Answers must be fairly common
export const MIN_GUESS_FREQUENCY = 4;   // Valid guesses can be less common

// Get frequency score for a word
export function getWordFrequency(word: string): number {
  return WORD_FREQUENCY_MAP[word.toUpperCase()] || DEFAULT_FREQUENCY;
}

// Check if word meets minimum frequency requirements
export function isFrequentEnoughForAnswers(word: string): boolean {
  return getWordFrequency(word) >= MIN_ANSWER_FREQUENCY;
}

export function isFrequentEnoughForGuesses(word: string): boolean {
  return getWordFrequency(word) >= MIN_GUESS_FREQUENCY;
}